name: Deployment

on: 
  push:
    branches:
      - master
    # paths:
      # - 'package.json'
jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: checkout for test
      uses: actions/checkout@v2
    - name: setup node using ${{ matrix.node-version }} 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: run tests
      run: |
        npm install
        npm run build:ts
        npm run test
    - name: build ui5 spa
      run: |
        npm run build-no-debug
      env:
        CI: true
    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.actions_deploy_secret }}
        EXTERNAL_REPOSITORY: wridgeu/wridgeu.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
      with:
        commitMessage: "PersonalPage upd."
        keepFiles: false #true
        emptyCommits: false
