# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build SPA & Deployment

on: 
  push:
    branches:
      - master
    # paths:
    #   - 'package.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: setup node using ${{ matrix.node-version }} 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
    - name: install chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable 
    - name: build
      run: |
        pnpm install --frozen-lockfile
        pnpm run build:deploy
      # pnpm run test:bg
      env:
        CI: true
    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.actions_deploy_secret }}
        EXTERNAL_REPOSITORY: wridgeu/wridgeu.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
      with:
        commitMessage: "PersonalPage upd."
        keepFiles: false #true
        emptyCommits: false
