name: build and publish personal website

on: 
  push:
    branches:
      - master
    paths:
      - 'package.json'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: use node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build personal website
      run: |
        npm i
        npm run build-no-debug
      env:
        CI: true
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.actions_deploy_secret }}
        EXTERNAL_REPOSITORY: wridgeu/wridgeu.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
      with:
        commitMessage: "PersonalPage upd."
        keepFiles: false #true
        emptyCommits: false
