name: Build SPA & Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup node using ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: build
        run: |
          npm ci
          npm run build:deploy
        env:
          CI: true
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.actions_deploy_secret }}
          external_repository: wridgeu/wridgeu.github.io
          publish_branch: master
          publish_dir: ./dist
          commitMessage: "PersonalPage upd."
          keepFiles: false
          emptyCommits: false
